language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t ahildreth/ci-cd_sandbox   -f Dockerfile.dev .

script:
  - docker run -e CI=true ahildreth/ci-cd_sandbox npm run test